export const GAME_CONFIG = Object.freeze({
  canvas: Object.freeze({
    width: 1024,
    height: 576,
  }),
  world: Object.freeze({
    width: 3520,
    height: 1216,
  }),
  movementSpeed: 192,
  maxDeltaSeconds: 0.05,
  camera: Object.freeze({
    zoom: 2.5,
  }),
  rooms: Object.freeze([
    Object.freeze({ id: "serverRoom", x: 64, y: 384, width: 896, height: 768, margin: 128, framePadding: 128 }),
    Object.freeze({
      id: "eastHall",
      x: 2560,
      y: 704,
      width: 896,
      height: 448,
      disableFog: true,
      marginTop: 64,
      framePadding: 128,
    }),
    Object.freeze({
      id: "stairsRoom",
      x: 2368,
      y: 128,
      width: 512,
      height: 448,
      framePadding: 128,
    }),
  ]),
  collision: Object.freeze({
    tileSize: 64,
    walkableTiles: Object.freeze([
      ".......................................................",
      ".......................####............................",
      ".......................#############.###########.......",
      ".......................#############.###########.......",
      ".......................####.......##.########.##.......",
      "..................................##.########.##.......",
      ".##############...................##.########.##.......",
      ".##############...................###########.##.......",
      ".##############...................###########.##.......",
      ".##############...............................##.......",
      ".##############.........................##############.",
      ".##############..........#####..........##############.",
      ".##############...####...#####...####...##############.",
      ".#####################################################.",
      ".#####################################################.",
      ".##############...####...#####...####...##############.",
      ".##############..........#####..........##############.",
      ".##############.........................##############.",
      ".......................................................",
    ]),
  }),
  assets: Object.freeze({
    map: "./assets/images/MapGrid.png",
    player: Object.freeze({
      down: "./assets/images/playerAction/Front.png",
      up: "./assets/images/playerAction/Back.png",
      left: "./assets/images/playerAction/Left.png",
      right: "./assets/images/playerAction/Right.png",
    }),
    monster: "./assets/images/shadow-monster.png",
    mimic: "./assets/images/미믹 1.png",
    barrier: "./assets/images/방벽 1.png",
    computer: "./assets/images/컴퓨터 1.png",
    earbuds: "./assets/images/에어팟 1.png",
  }),
  mapCrop: Object.freeze({
    x: 301,
    y: 529,
    width: 3520,
    height: 1216,
  }),
  player: Object.freeze({
    x: 1536,
    y: 192,
    size: 64,
    footInsetX: 14,
    footInsetY: 8,
    collisionInsetX: 16,
    collisionTop: 32,
    collisionBottom: 4,
    animationFrameCount: 4,
    animationFrameDuration: 0.14,
  }),
  encounters: Object.freeze([
    Object.freeze({
      id: "hallwayShadow",
      eventId: "hallwayShadow",
      x: 2176,
      y: 128,
      size: 128,
      collisionInsetX: 0,
      collisionTop: 0,
      collisionBottom: 0,
    }),
  ]),
  mimic: Object.freeze({
    x: 1664,
    y: 768,
    size: 192,
  }),
  barrier: Object.freeze({
    x: 2176,
    y: 768,
    width: 64,
    height: 256,
  }),
  computer: Object.freeze({
    x: 2304,
    y: 768,
    size: 64,
  }),
  goal: Object.freeze({
    x: 2230,
    y: 195,
    size: 60,
  }),
  pickups: Object.freeze([
    Object.freeze({
      id: "earbudsPickup",
      itemId: "noiseCancelingEarbuds",
      x: 1824,
      y: 184,
      size: 48,
    }),
  ]),
  stats: Object.freeze({
    startMinutes: 17 * 60,
    limitMinutes: 18 * 60,
    hpMax: 100,
    cringeMax: 100,
  }),
});
