export const GAME_CONFIG = Object.freeze({
  canvas: Object.freeze({
    width: 1024,
    height: 576,
  }),
  world: Object.freeze({
    width: 3520,
    height: 1216,
  }),
  movementSpeed: 192,
  maxDeltaSeconds: 0.05,
  camera: Object.freeze({
    zoom: 2.5,
  }),
  rooms: Object.freeze([
    Object.freeze({ id: "serverRoom", x: 64, y: 384, width: 896, height: 768, margin: 128, framePadding: 128 }),
    Object.freeze({
      id: "eastHall",
      x: 2560,
      y: 704,
      width: 896,
      height: 448,
      disableFog: true,
      marginTop: 64,
      framePadding: 128,
    }),
    Object.freeze({
      id: "stairsRoom",
      x: 2368,
      y: 128,
      width: 512,
      height: 448,
      framePadding: 128,
    }),
  ]),
  collision: Object.freeze({
    tileSize: 64,
    walkableTiles: Object.freeze([
      ".......................................................",
      ".......................####............................",
      ".......................#############.###########.......",
      ".......................#############.###########.......",
      ".......................####.......##.########.##.......",
      "..................................##.########.##.......",
      ".##############...................##.########.##.......",
      ".##############...................###########.##.......",
      ".##############...................###########.##.......",
      ".##############...............................##.......",
      ".##############.........................##############.",
      ".##############..........#####..........##############.",
      ".##############...####...#####...####...##############.",
      ".#####################################################.",
      ".#####################################################.",
      ".##############...####...#####...####...##############.",
      ".##############..........#####..........##############.",
      ".##############.........................##############.",
      ".......................................................",
    ]),
  }),
  assets: Object.freeze({
    map: "./assets/images/MapGrid.png",
    player: Object.freeze({
      down: "./assets/images/playerAction/Front.png",
      up: "./assets/images/playerAction/Back.png",
      left: "./assets/images/playerAction/Left.png",
      right: "./assets/images/playerAction/Right.png",
    }),
    monster: "./assets/images/shadowMonsterAction/shadow-monster.png",
    monsterDefeat: "./assets/images/shadowMonsterAction/그림자-괴물_죽음 1.png",
    mimic: "./assets/images/미믹 1.png",
    barrier: "./assets/images/방벽 1.png",
    computer: "./assets/images/컴퓨터 1.png",
    earbuds: "./assets/images/에어팟 1.png",
    office: Object.freeze({
      principalIdle: "./assets/images/교장Assets/교장_눈치 못챔 2.png",
      principalSuspicious: "./assets/images/교장Assets/교장_확인함 1.png",
      principalAlert: "./assets/images/교장Assets/교장_확인함 2.png",
      sofa: "./assets/images/교장Assets/쇼파 1.png",
      vases: Object.freeze([
        "./assets/images/교장Assets/꽃병 1.png",
        "./assets/images/교장Assets/꽃병 2.png",
        "./assets/images/교장Assets/꽃병 3.png",
        "./assets/images/교장Assets/꽃병 4.png",
      ]),
    }),
  }),
  monsterDefeat: Object.freeze({
    frameCount: 4,
    frameDuration: 0.14,
  }),
  mapCrop: Object.freeze({
    x: 301,
    y: 529,
    width: 3520,
    height: 1216,
  }),
  player: Object.freeze({
    x: 1536,
    y: 192,
    size: 64,
    footInsetX: 14,
    footInsetY: 8,
    collisionInsetX: 16,
    collisionTop: 32,
    collisionBottom: 4,
    animationFrameCount: 4,
    animationFrameDuration: 0.14,
  }),
  encounters: Object.freeze([
    Object.freeze({
      id: "hallwayShadow",
      eventId: "hallwayShadow",
      x: 2176,
      y: 128,
      size: 128,
      collisionInsetX: 0,
      collisionTop: 0,
      collisionBottom: 0,
    }),
  ]),
  mimic: Object.freeze({
    x: 1664,
    y: 768,
    size: 192,
  }),
  barrier: Object.freeze({
    x: 2176,
    y: 768,
    width: 64,
    height: 256,
  }),
  computer: Object.freeze({
    x: 2304,
    y: 768,
    size: 64,
  }),
  goal: Object.freeze({
    x: 2240,
    y: 768,
    size: 60,
  }),
  pickups: Object.freeze([
    Object.freeze({
      id: "earbudsPickup",
      itemId: "noiseCancelingEarbuds",
      x: 1824,
      y: 184,
      size: 48,
    }),
  ]),
  office: Object.freeze({
    bounds: Object.freeze({ x: 2304, y: 128, width: 576, height: 448 }),
    principal: Object.freeze({ x: 2496, y: 128, size: 128 }),
    sofa: Object.freeze({ x: 2432, y: 384, width: 256, height: 64 }),
    safeZone: Object.freeze({ x: 2432, y: 448, width: 256, height: 128 }),
    principalTiming: Object.freeze({ seatedSeconds: 3, suspiciousSeconds: 1, alertSeconds: 1 }),
    revealDuration: 0.65,
    vases: Object.freeze([
      Object.freeze({ x: 2816, y: 64, size: 64 }),
      Object.freeze({ x: 2880, y: 64, size: 64 }),
      Object.freeze({ x: 2944, y: 64, size: 64 }),
      Object.freeze({ x: 3008, y: 64, size: 64 }),
    ]),
    alertDamagePerSecond: 80,
    vaseAttack: Object.freeze({
      trigger: Object.freeze({ x: 2944, y: 448, width: 128, height: 128 }),
      sourceVaseIndexes: Object.freeze([2, 3]),
      fallSpeed: 720,
      shotDelay: 0.55,
      damage: 30,
      projectileSize: 40,
    }),
  }),
  stats: Object.freeze({
    startMinutes: 17 * 60,
    limitMinutes: 18 * 60,
    hpMax: 100,
    cringeMax: 100,
  }),
});
